### PR TITLE
Wayland

### PR DESCRIPTION
**Pull request by faveoled**
Not tested

### CODE REVIEW

**Comment by Altonss** [comment]
As is it doesn't work, I already tried it.
Please only open PRs for tested changes.

**Comment by faveoled** [comment]
How exactly does it fail?

**Comment by Altonss** [comment]
This is displayed `(hypnotix.py:10): Gtk-WARNING **: 14:48:43.483: cannot open display: ` and then nothing displays.
It's probably related to:
https://github.com/linuxmint/hypnotix/blob/284e4e13b1e0f03ac4546d5139854bbeb2581954/usr/lib/hypnotix/hypnotix.py#L15-L16
I'll try to see if I can do something :)

**Comment by Altonss** [comment]
Quickly tried to find a fix, but couldn't make it work. I won't spend more time on this as it's working seemlessly on x11 and upstream is also favoring x11 :)
But I'll happily review a tested PR to bring wayland :)

**Pull request closed without merging**
